apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  strategy:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.pod_annotations }}
      annotations:
        {{- range $key, $value := .Values.pod_annotations }}
        {{ $key }}: {{ $value }} {{ end }}{{ end }}
      labels:
        app: {{ .Release.Name }}
      name: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      containers:
      - image: "{{ .Values.image }}:{{ .Values.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: {{ .Release.Name }}
        env:
          {{- range $key, $val := .Values.environment }}
          - name: {{ $key }}
            value: {{ $val | quote }} {{ end }}
        volumeMounts:
          - mountPath: "/etc/credentials"
            name: google-credentials
            readOnly: true
{{- if .Values.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}{{- end }}
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 12 }}{{- end }}
      volumes:
        - name: google-credentials
          secret:
            defaultMode: 420
            secretName: {{ .Release.Name }}-credentials
